# Generated by Django 4.1.3 on 2022-12-30 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="langague",
            new_name="language",
        ),
    ]
